@echo off
echo Fixing axios import error and reinstalling dependencies...

echo Step 1: Stopping any running dev servers...
taskkill /f /im node.exe 2>nul

echo Step 2: Removing node_modules...
if exist node_modules (
    echo Removing node_modules directory...
    rmdir /s /q node_modules 2>nul
) else (
    echo node_modules directory not found, skipping...
)

echo Step 3: Removing package-lock.json...
if exist package-lock.json (
    echo Removing package-lock.json...
    del package-lock.json 2>nul
) else (
    echo package-lock.json not found, skipping...
)

echo Step 4: Clearing npm cache...
npm cache clean --force

echo Step 5: Installing dependencies...
npm install

echo Step 6: Verifying axios installation...
npm list axios

echo Step 7: Starting development server...
npm run dev

pause
